@baseUrl = http://localhost:8080/api/v1
@userId = REPLACE_WITH_USER_UUID
@categoryId = REPLACE_WITH_CATEGORY_UUID
@postId = REPLACE_WITH_POST_UUID

###

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Gryffin",
    "email": "gryffin.devops@uit.edu.vn",
    "password": "supersecretpassword123"
}

###

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "gryffin.devops@uit.edu.vn",
    "password": "supersecretpassword123"
}

###

POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "DevOps & Home Lab"
}

###

GET {{baseUrl}}/categories

###

POST {{baseUrl}}/posts
Content-Type: application/json

{
    "title": "Hướng dẫn setup K3s trên KVM",
    "content": "Ghi chú quá trình build môi trường Kubernetes nhẹ nhàng trên máy ảo Debian...",
    "author_id": "81f159ea-b68b-4dc1-9fae-0b4b5542be35",
    "category_id": "57175fc9-583a-4604-b0b3-134e1d0fbcab",
    "status": "published"
}

###

GET {{baseUrl}}/posts

###

GET {{baseUrl}}/posts/huong-dan-setup-k3s-tren-kvm

###

DELETE {{baseUrl}}/posts/cebe2066-7668-4782-8a74-877639c6cce0