// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Category struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	CreatedAt time.Time
}

type Post struct {
	ID         uuid.UUID
	Title      string
	Slug       string
	Content    string
	AuthorID   uuid.UUID
	CategoryID uuid.NullUUID
	Status     string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
	Name      string
}
